
CREATE TABLE POST (
    ID INT NOT NULL UNIQUE,
    FOREIGN KEY (ID) REFERENCES usuario(ID) ON DELETE CASCADE,
    GTESTE BOOL DEFAULT TRUE NOT NULL,
    HGGH BOOLEAN DEFAULT FALSE NOT NULL,
    idade BIT(64) NOT NULL
);


